export const stagingNetworks = {
  883: {
    name: "883",
    color: "#3099f2",
    chainId: 883,
    rpcUrl: "http://localhost:8545",
    blockTime: 5000,
    iconUrl: "./noChain.png",
    blockDelay: 15,
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  884: {
    name: "884",
    color: "#3099f2",
    chainId: 884,
    rpcUrl: "http://localhost:8547",
    blockTime: 5000,
    iconUrl: "./noChain.png",
    blockDelay: 15,
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  localhost: {
    name: "--",
    color: "#666666",
    chainId: 31337,
    rpcUrl: "http://localhost:8545",
    blockTime: 3000,
    iconUrl: "./defaultIcon.svg",
    blockDelay: 4,
    symbol: "ETH",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  bscTest: {
    name: "BSC Testnet",
    color: "#7057ff",
    chainId: 97,
    rpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
    blockTime: 4000,
    iconUrl: "./bsc.png",
    blockDelay: 80,
    symbol: "BNB",
    blockExplorerUrl: "https://testnet.bscscan.com",
    tokenSymbolList: ["CELR", "USDT", "WETH", "DOMI", "MCB", "PSP", "PCE", "MELI"],
    lqMintTokenSymbolBlackList: ["DOMI", "PSP", "MELI"],
  },
  ropsten: {
    name: "Ropsten Testnet",
    color: "#ff4a8d",
    chainId: 3,
    rpcUrl: "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 4,
    symbol: "ETH",
    blockExplorerUrl: "https://ropsten.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  goerli: {
    name: "Goerli Testnet",
    color: "#3099f2",
    chainId: 5,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 4,
    symbol: "ETH",
    blockExplorerUrl: "https://goerli.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH", "TCELR", "USDC", "DOMI", "MCB", "cUSD", "PSP"],
    contractAddr: "0x358234B325EF9eA8115291A8b81b7d33A2Fa762D",
    lqMintTokenSymbolBlackList: ["DOMI", "cUSD", "PSP"],
  },
  mainnet: {
    name: "Ethereum Mainnet",
    color: "#29b6af",
    chainId: 1,
    rpcUrl: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "LYRA",
      "DOMI",
      "MCB",
      "IMX",
      "oneDODO",
      "OLO",
      "BOBA",
      "XTK",
      "xXTKa",
      "PSP",
      "FRAX",
      "CVP",
      "CEC",
      "Metis",
      "WXT",
      "PEOPLE",
      "STND",
      "SOS",
      "WBTC",
      "CELR",
      "WOO",
      "DF",
      "USX",
      "AMY",
    ],
    lqMintTokenSymbolBlackList: [
      "DOMI",
      "oneDODO",
      "OLO",
      "PSP",
      "FRAX",
      "WXT",
      "PEOPLE",
      "SOS",
      "WBTC",
      "CELR",
      "AMY",
    ],
  },
  bsc: {
    name: "BSC",
    color: "#7057ff",
    chainId: 56,
    rpcUrl: "https://bsc-dataseed.binance.org",
    blockTime: 4000,
    iconUrl: "./bsc.png",
    blockDelay: 8,
    symbol: "BNB",
    blockExplorerUrl: "https://bscscan.com",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "DOMI",
      "MCB",
      "cUSD",
      "oneDODO",
      "OLO",
      "PSP",
      "FRAX",
      "CVP",
      "CEC",
      "ATL",
      "PEOPLE",
      "SOS",
      "BNB",
      "WOO",
      "DF",
      "USX",
    ],
    lqMintTokenSymbolBlackList: ["DOMI", "cUSD", "oneDODO", "OLO", "PSP", "FRAX", "ATL", "PEOPLE", "SOS", "BNB"],
  },

  polygon: {
    name: "Polygon (Matic)",
    color: "#3099f2",
    chainId: 137,
    rpcUrl: "https://polygon-rpc.com",
    blockTime: 4000,
    iconUrl: "./polygon.png",
    blockDelay: 80,
    symbol: "MATIC",
    blockExplorerUrl: "https://polygonscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "IMX", "FRAX", "WXT", "ATL", "MAI", "WOO"],
    lqMintTokenSymbolBlackList: ["FRAX", "WXT", "ATL", "MAI"],
  },
  arbitrum: {
    name: "Arbitrum",
    color: "#ff4a8d",
    chainId: 42161,
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    blockTime: 4000,
    iconUrl: "./arbitrum.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://arbiscan.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "DODO", "MCB", "IMX", "XTK", "xXTKa", "FRAX", "WOO", "DF", "USX", "AMY"],
    lqMintTokenSymbolBlackList: ["FRAX", "AMY"],
  },
  Avalanche: {
    name: "Avalanche",
    color: "#3099f2",
    chainId: 43114,
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    blockTime: 5000,
    iconUrl: "./avalanche.png",
    blockDelay: 15,
    symbol: "AVAX",
    blockExplorerUrl: "https://snowtrace.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "IMX", "FRAX", "WXT", "PEOPLE", "MAI", "SOS", "AVAX", "WOO", "ATL"],
    lqMintTokenSymbolBlackList: ["FRAX", "WXT", "PEOPLE", "MAI", "SOS", "AVAX", "ATL"],
  },
  Optimism: {
    name: "Optimism",
    color: "#3099f2",
    chainId: 10,
    rpcUrl: "https://mainnet.optimism.io",
    blockTime: 5000,
    iconUrl: "./optimism.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://optimistic.etherscan.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "LYRA", "DF", "USX"],
    lqMintTokenSymbolBlackList: [],
  },
  OptimisticKovan: {
    name: "Optimistic Kovan",
    color: "#3099f2",
    chainId: 69,
    rpcUrl: "https://kovan.optimism.io",
    blockTime: 5000,
    iconUrl: "./optimism.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://kovan-optimistic.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  Fantom: {
    name: "Fantom",
    color: "#3099f2",
    chainId: 250,
    rpcUrl: "https://rpc.ftm.tools",
    blockTime: 5000,
    iconUrl: "./fantom.png",
    blockDelay: 6,
    symbol: "FTM",
    blockExplorerUrl: "https://ftmscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "FRAX", "PEOPLE", "SOS", "WOO", "FTM"],
    lqMintTokenSymbolBlackList: ["FRAX", "PEOPLE", "SOS", "FTM"],
  },
  FantomTestnet: {
    name: "Fantom Testnet",
    color: "#3099f2",
    chainId: 4002,
    rpcUrl: "https://rpc.testnet.fantom.network",
    blockTime: 5000,
    iconUrl: "./fantom.png",
    blockDelay: 6,
    symbol: "FTM",
    blockExplorerUrl: "https://testnet.ftmscan.com",
    tokenSymbolList: ["CELR", "USDT", "TCELR"],
    lqMintTokenSymbolBlackList: [],
  },

  Harmony: {
    name: "Harmony",
    color: "#3099f2",
    chainId: 1666600000,
    rpcUrl: "https://api.harmony.one",
    blockTime: 5000,
    iconUrl: "./harmony.png",
    blockDelay: 20,
    symbol: "ONE",
    blockExplorerUrl: "https://explorer.harmony.one",
    tokenSymbolList: ["USDC", "WETH", "FRAX", "PEOPLE", "MAI", "SOS"],
    lqMintTokenSymbolBlackList: ["FRAX", "PEOPLE", "MAI", "SOS"],
  },

  Moonriver: {
    name: "Moonriver",
    color: "#3099f2",
    chainId: 1285,
    rpcUrl: "https://rpc.moonriver.moonbeam.network",
    blockTime: 5000,
    iconUrl: "./moonriver.png",
    blockDelay: 20,
    symbol: "MOVR",
    blockExplorerUrl: "https://moonriver.moonscan.io",
    tokenSymbolList: ["SOS", "FRAX", "PEOPLE", "USDC", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: ["SOS", "FRAX", "PEOPLE", "USDC", "USDT", "WETH"],
  },

  BoBa: {
    name: "Boba Network",
    color: "#3099f2",
    chainId: 288,
    rpcUrl: "https://mainnet.boba.network",
    blockTime: 10000,
    iconUrl: "./boba.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://blockexplorer.boba.network",
    tokenSymbolList: ["USDC", "OLO", "BOBA", "FRAX"],
    lqMintTokenSymbolBlackList: ["OLO", "FRAX"],
  },

  CeloTestnet: {
    name: "Celo Testnet",
    color: "#3099f2",
    chainId: 44787,
    rpcUrl: "https://alfajores-forno.celo-testnet.org",
    blockTime: 10000,
    iconUrl: "./celo.png",
    blockDelay: 8,
    symbol: "CELO",
    blockExplorerUrl: "https://alfajores-blockscout.celo-testnet.org",
    tokenSymbolList: ["USDC", "cUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "cUSD"],
  },

  Celo: {
    name: "Celo",
    color: "#3099f2",
    chainId: 42220,
    rpcUrl: "https://forno.celo.org",
    blockTime: 10000,
    iconUrl: "./celo.png",
    blockDelay: 8,
    symbol: "CELO",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["USDC", "USDT", "cUSD", "WETH", "PEOPLE", "SOS"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "cUSD", "WETH", "PEOPLE", "SOS"],
  },

  OKExChainTestnet: {
    name: "OKExChain Testnet",
    color: "#3099f2",
    chainId: 65,
    rpcUrl: "https://exchaintestrpc.okex.org",
    blockTime: 10000,
    iconUrl: "./OKchain.png",
    blockDelay: 8,
    symbol: "PCE",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["PCE", "MELI"],
    lqMintTokenSymbolBlackList: ["MELI"],
  },

  Aurora: {
    name: "Aurora",
    color: "#3099f2",
    chainId: 1313161554,
    rpcUrl: "https://mainnet.aurora.dev",
    blockTime: 10000,
    iconUrl: "./Aurora.png",
    blockDelay: 8,
    symbol: "aETH",
    blockExplorerUrl: "https://explorer.mainnet.aurora.dev/",
    tokenSymbolList: ["USDC", "BNB", "AVAX", "FTM"],
    lqMintTokenSymbolBlackList: ["BNB", "AVAX", "FTM"],
  },

  Metis: {
    name: "Metis",
    color: "#3099f2",
    chainId: 1088,
    rpcUrl: "https://andromeda.metis.io/?owner=1088",
    blockTime: 10000,
    iconUrl: "./metis_chain.png",
    blockDelay: 8,
    symbol: "Metis",
    blockExplorerUrl: "https://andromeda-explorer.metis.io/",
    tokenSymbolList: ["Metis", "STND", "PEOPLE", "WBTC", "CELR", "SOS"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "WBTC", "CELR", "SOS"],
  },

  OKExChain: {
    name: "OKExChain Mainnet",
    color: "#3099f2",
    chainId: 66,
    rpcUrl: "https://exchainrpc.okex.org",
    blockTime: 10000,
    iconUrl: "./oec.png",
    blockDelay: 8,
    symbol: "OKT",
    blockExplorerUrl: "https://www.oklink.com/en/oec",
    tokenSymbolList: ["PEOPLE", "SOS"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "SOS"],
  },

  xDai: {
    name: "xDai",
    color: "#3099f2",
    chainId: 100,
    rpcUrl: "https://rpc.xdaichain.com",
    blockTime: 10000,
    iconUrl: "./xdai.png",
    blockDelay: 8,
    symbol: "xDai",
    blockExplorerUrl: "https://blockscout.com/xdai/mainnet",
    tokenSymbolList: ["PEOPLE", "SOS"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "SOS"],
  },

  Heco: {
    name: "Heco",
    color: "#3099f2",
    chainId: 128,
    rpcUrl: "https://http-mainnet.hecochain.com",
    blockTime: 10000,
    iconUrl: "./heco.png",
    blockDelay: 8,
    symbol: "HT",
    blockExplorerUrl: "https://hecoinfo.com",
    tokenSymbolList: ["PEOPLE", "SOS"],
    lqMintTokenSymbolBlackList: ["PEOPLE", "SOS"],
  },

  Oasis: {
    name: "Oasis Emerald",
    color: "#3099f2",
    chainId: 42262,
    rpcUrl: "https://emerald.oasis.dev",
    blockTime: 10000,
    iconUrl: "./oasis.png",
    blockDelay: 8,
    symbol: "ROSE",
    blockExplorerUrl: "https://www.oasisscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "BNB", "AVAX", "FTM", "AMY"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "WETH", "BNB", "AVAX", "FTM", "AMY"],
  },
};
