export const stagingNetworks = {
  mainnet: {
    name: "Ethereum Mainnet",
    color: "#29b6af",
    chainId: 1,
    rpcUrl: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "LYRA",
      "DOMI",
      "MCB",
      "IMX",
      "oneDODO",
      "OLO",
      "BOBA",
      "XTK",
      "xXTKa",
      "PSP",
      "FRAX",
      "FXS",
      "CVP",
      "CEC",
      "Metis",
      "WXT",
      "PEOPLE",
      "STND",
      "SOS",
      "WBTC",
      "CELR",
      "WOO",
      "DF",
      "USX",
      "AMY",
      "DAI",
      "GHX",
      "KROM",
      "PERP",
      "TCR",
      "SAFLE",
      "PKEX",
      "CONV",
      "PERL",
      "TSD",
      "AAVE",
      "CRV",
      "SYS",
      "AVG",
      "AELIN",
      "JPEG",
      "CGG",
      "REVA",
      "MASK",
      "LUSD",
      "WAGMIV1",
      "REEF",
      "THALES",
      "DODO",
      "MELOS",
      "TORN",
      "MSU",
      "UCG",
      "HUH",
      "iZi",
      "ESW",
      "MGH",
      "ASTR",
      "BLANK",
      "ANML",
      "GOVI",
      "ONG",
      "DTR",
      "WAGMIV2",
      "RING",
      "DEVT",
      "GEL",
      "NFTY",
      "RLY",
      "AKRO",
      "MUX",
      "SHI",
    ],
  },
  bsc: {
    name: "BNB Chain",
    color: "#7057ff",
    chainId: 56,
    rpcUrl: "https://bsc-dataseed.binance.org",
    blockTime: 4000,
    iconUrl: "./bnbchain.png",
    blockDelay: 8,
    symbol: "BNB",
    blockExplorerUrl: "https://bscscan.com",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "DOMI",
      "MCB",
      "cUSD",
      "oneDODO",
      "OLO",
      "PSP",
      "FRAX",
      "FXS",
      "CVP",
      "CEC",
      "ATL",
      "PEOPLE",
      "SOS",
      "BNB",
      "WOO",
      "DF",
      "USX",
      "GHX",
      "PERP",
      "SAFLE",
      "PERL",
      "WBNB",
      "TSD",
      "SYS",
      "AVG",
      "JPEG",
      "REVA",
      "MASK",
      "LUSD",
      "REEF",
      "SWAY",
      "JADE",
      "MELOS",
      "TORN",
      "MSU",
      "UCG",
      "HUH",
      "MGH",
      "ASVA",
      "ANML",
      "iZi",
      "ONG",
      "DTR",
      "AKRO",
      "MUXLP",
      "muxUSD",
      "muxETH",
      "muxBTC",
      "muxBNB",
      "muxAVAX",
      "muxFTM",
      "SHI",
      "PEEL",
      "SHELL",
    ],
  },
};
