export const stagingNetworks = {
  mainnet: {
    name: "Ethereum Mainnet",
    color: "#29b6af",
    chainId: 1,
    rpcUrl: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "LYRA",
      "DOMI",
      "MCB",
      "IMX",
      "oneDODO",
      "OLO",
      "BOBA",
      "XTK",
      "xXTKa",
      "PSP",
      "FRAX",
      "CVP",
      "CEC",
      "Metis",
      "WXT",
      "PEOPLE",
      "STND",
      "SOS",
      "WBTC",
      "CELR",
      "WOO",
      "DF",
      "USX",
      "AMY",
      "DAI",
      "GHX",
      "KROM",
      "PERP",
      "TCR",
      "SAFLE",
      "WREVA",
    ],
  },
  bsc: {
    name: "BSC",
    color: "#7057ff",
    chainId: 56,
    rpcUrl: "https://bsc-dataseed.binance.org",
    blockTime: 4000,
    iconUrl: "./bsc.png",
    blockDelay: 8,
    symbol: "BNB",
    blockExplorerUrl: "https://bscscan.com",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "DOMI",
      "MCB",
      "cUSD",
      "oneDODO",
      "OLO",
      "PSP",
      "FRAX",
      "CVP",
      "CEC",
      "ATL",
      "PEOPLE",
      "SOS",
      "BNB",
      "WOO",
      "DF",
      "USX",
      "GHX",
      "PERP",
      "SAFLE",
      "WREVA",
    ],
  },
};
