export const testNetworks = {
  883: {
    name: "883",
    color: "#3099f2",
    chainId: 883,
    rpcUrl: "http://localhost:8545",
    blockTime: 5000,
    iconUrl: "./noChain.png",
    blockDelay: 15,
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  884: {
    name: "884",
    color: "#3099f2",
    chainId: 884,
    rpcUrl: "http://localhost:8547",
    blockTime: 5000,
    iconUrl: "./noChain.png",
    blockDelay: 15,
    symbol: "",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  localhost: {
    name: "--",
    color: "#666666",
    chainId: 31337,
    rpcUrl: "http://localhost:8545",
    blockTime: 3000,
    iconUrl: "./defaultIcon.svg",
    blockDelay: 4,
    symbol: "ETH",
    blockExplorerUrl: "",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: [],
  },
  bscTest: {
    name: "BSC Testnet",
    color: "#7057ff",
    chainId: 97,
    rpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
    blockTime: 4000,
    iconUrl: "./bsc.png",
    blockDelay: 80,
    symbol: "BNB",
    blockExplorerUrl: "https://testnet.bscscan.com",
    tokenSymbolList: ["CELR", "USDT", "WETH", "MCB", "PSP", "PCE", "MELI"],
    lqMintTokenSymbolBlackList: ["PSP", "MELI"],
  },
  ropsten: {
    name: "Ropsten Testnet",
    color: "#ff4a8d",
    chainId: 3,
    rpcUrl: "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 4,
    symbol: "ETH",
    blockExplorerUrl: "https://ropsten.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  goerli: {
    name: "Goerli Testnet",
    color: "#3099f2",
    chainId: 5,
    rpcUrl: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 4,
    symbol: "ETH",
    blockExplorerUrl: "https://goerli.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH", "TCELR", "USDC", "DOMI", "MCB", "cUSD", "PSP"],
    contractAddr: "0x358234B325EF9eA8115291A8b81b7d33A2Fa762D",
    lqMintTokenSymbolBlackList: ["DOMI", "cUSD", "PSP"],
  },
  mainnet: {
    name: "Ethereum Mainnet",
    color: "#29b6af",
    chainId: 1,
    rpcUrl: "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
    blockTime: 15000,
    iconUrl: "./ETH.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://etherscan.io",
    tokenSymbolList: [
      "USDC",
      "USDT",
      "WETH",
      "BUSD",
      "DODO",
      "LYRA",
      "DOMI",
      "MCB",
      "IMX",
      "oneDODO",
      "OLO",
      "BOBA",
      "FRAX",
    ],
    lqMintTokenSymbolBlackList: ["DOMI", "oneDODO", "OLO", "FRAX"],
  },
  bsc: {
    name: "BSC",
    color: "#7057ff",
    chainId: 56,
    rpcUrl: "https://bsc-dataseed.binance.org",
    blockTime: 4000,
    iconUrl: "./bsc.png",
    blockDelay: 8,
    symbol: "BNB",
    blockExplorerUrl: "https://bscscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "BUSD", "DODO", "DOMI", "MCB", "cUSD", "oneDODO", "OLO", "FRAX"],
    lqMintTokenSymbolBlackList: ["DOMI", "cUSD", "oneDODO", "OLO", "FRAX"],
  },

  polygon: {
    name: "Polygon (Matic)",
    color: "#3099f2",
    chainId: 137,
    rpcUrl: "https://polygon-rpc.com",
    blockTime: 4000,
    iconUrl: "./polygon.png",
    blockDelay: 80,
    symbol: "MATIC",
    blockExplorerUrl: "https://polygonscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH", "IMX"],
    lqMintTokenSymbolBlackList: [],
  },
  arbitrum: {
    name: "Arbitrum",
    color: "#ff4a8d",
    chainId: 42161,
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    blockTime: 4000,
    iconUrl: "./arbitrum.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://arbiscan.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "DODO", "MCB", "IMX"],
    lqMintTokenSymbolBlackList: [],
  },
  Avalanche: {
    name: "Avalanche",
    color: "#3099f2",
    chainId: 43114,
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    blockTime: 5000,
    iconUrl: "./avalanche.png",
    blockDelay: 15,
    symbol: "AVAX",
    blockExplorerUrl: "https://snowtrace.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "IMX"],
    lqMintTokenSymbolBlackList: [],
  },
  Optimism: {
    name: "Optimism",
    color: "#3099f2",
    chainId: 10,
    rpcUrl: "https://mainnet.optimism.io",
    blockTime: 5000,
    iconUrl: "./optimism.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://optimistic.etherscan.io",
    tokenSymbolList: ["USDC", "USDT", "WETH", "LYRA"],
    lqMintTokenSymbolBlackList: [],
  },
  OptimisticKovan: {
    name: "Optimistic Kovan",
    color: "#3099f2",
    chainId: 69,
    rpcUrl: "https://kovan.optimism.io",
    blockTime: 5000,
    iconUrl: "./optimism.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://kovan-optimistic.etherscan.io",
    tokenSymbolList: ["CELR", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  Fantom: {
    name: "Fantom",
    color: "#3099f2",
    chainId: 250,
    rpcUrl: "https://rpc.ftm.tools",
    blockTime: 5000,
    iconUrl: "./fantom.png",
    blockDelay: 6,
    symbol: "FTM",
    blockExplorerUrl: "https://ftmscan.com",
    tokenSymbolList: ["USDC", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: [],
  },
  FantomTestnet: {
    name: "Fantom Testnet",
    color: "#3099f2",
    chainId: 4002,
    rpcUrl: "https://rpc.testnet.fantom.network",
    blockTime: 5000,
    iconUrl: "./fantom.png",
    blockDelay: 6,
    symbol: "FTM",
    blockExplorerUrl: "https://testnet.ftmscan.com",
    tokenSymbolList: ["CELR", "USDT", "TCELR", "WETH"],
    lqMintTokenSymbolBlackList: ["WETH"],
  },

  // Harmony: {
  //   name: "Harmony",
  //   color: "#3099f2",
  //   chainId: 1666600000,
  //   rpcUrl: "https://api.harmony.one",
  //   blockTime: 5000,
  //   iconUrl: "./harmony.png",
  //   blockDelay: 20,
  //   symbol: "ONE",
  //   blockExplorerUrl: "https://explorer.harmony.one",
  //   tokenSymbolList: ["USDC", "WETH"],
  // lqMintTokenSymbolBlackList:[]
  // },

  // Moonriver: {
  //   name: "Moonriver",
  //   color: "#3099f2",
  //   chainId: 1285,
  //   rpcUrl: "https://rpc.moonriver.moonbeam.network",
  //   blockTime: 5000,
  //   iconUrl: "./moonriver.png",
  //   blockDelay: 20,
  //   symbol: "MOVR",
  //   blockExplorerUrl: "https://moonriver.moonscan.io",
  //   tokenSymbolList: ["USDC"],
  // lqMintTokenSymbolBlackList:[]
  // },

  BoBa: {
    name: "Boba Network",
    color: "#3099f2",
    chainId: 288,
    rpcUrl: "https://mainnet.boba.network",
    blockTime: 10000,
    iconUrl: "./boba.png",
    blockDelay: 8,
    symbol: "ETH",
    blockExplorerUrl: "https://blockexplorer.boba.network",
    tokenSymbolList: ["USDC", "OLO", "BOBA"],
    lqMintTokenSymbolBlackList: ["OLO"],
  },

  CeloTestnet: {
    name: "Celo Testnet",
    color: "#3099f2",
    chainId: 44787,
    rpcUrl: "https://alfajores-forno.celo-testnet.org",
    blockTime: 10000,
    iconUrl: "./celo.png",
    blockDelay: 8,
    symbol: "CELO",
    blockExplorerUrl: "https://alfajores-blockscout.celo-testnet.org",
    tokenSymbolList: ["USDC", "cUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "cUSD"],
  },

  Celo: {
    name: "Celo",
    color: "#3099f2",
    chainId: 42220,
    rpcUrl: "https://forno.celo.org",
    blockTime: 10000,
    iconUrl: "./celo.png",
    blockDelay: 8,
    symbol: "CELO",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["USDC", "USDT", "cUSD"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "cUSD"],
  },

  OKExChainTestnet: {
    name: "OKExChain Testnet",
    color: "#3099f2",
    chainId: 65,
    rpcUrl: "https://exchaintestrpc.okex.org",
    blockTime: 10000,
    iconUrl: "./OKchain.png",
    blockDelay: 8,
    symbol: "PCE",
    blockExplorerUrl: "https://explorer.celo.org",
    tokenSymbolList: ["PCE", "MELI"],
    lqMintTokenSymbolBlackList: ["MELI"],
  },
  MoonbaseAlpha: {
    name: "Moonbase Alpha",
    color: "#3099f2",
    chainId: 1287,
    rpcUrl: "https://rpc.testnet.moonbeam.network",
    blockTime: 10000,
    iconUrl: "./moonriver.png",
    blockDelay: 8,
    symbol: "DEV",
    blockExplorerUrl: "https://moonbase-blockscout.testnet.moonbeam.network/",
    tokenSymbolList: ["USDC", "USDT", "WETH"],
    lqMintTokenSymbolBlackList: ["USDC", "USDT", "WETH"],
  },

  REITestnet: {
    name: "REI Testnet",
    color: "#3099f2",
    chainId: 12357,
    rpcUrl: "https://rpc-testnet.rei.network",
    blockTime: 10000,
    iconUrl: "./GXChain.png",
    blockDelay: 8,
    symbol: "DEV",
    blockExplorerUrl: "https://scan-test.rei.network",
    tokenSymbolList: ["USDC"],
    lqMintTokenSymbolBlackList: ["USDC"],
  },

  OasisTestnet: {
    name: "Emerald Paratime Testnet",
    color: "#3099f2",
    chainId: 42261,
    rpcUrl: "https://testnet.emerald.oasis.dev",
    blockTime: 10000,
    iconUrl: "./oasis.png",
    blockDelay: 8,
    symbol: "ROSE",
    blockExplorerUrl: "https://explorer.testnet.oasis.updev.si",
    tokenSymbolList: ["USDT"],
    lqMintTokenSymbolBlackList: ["USDT"],
  },
};
