/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface OriginalTokenVaultV2Interface extends utils.Interface {
  contractName: "OriginalTokenVaultV2";
  functions: {
    "addGovernor(address)": FunctionFragment;
    "addPauser(address)": FunctionFragment;
    "delayPeriod()": FunctionFragment;
    "delayThresholds(address)": FunctionFragment;
    "delayedTransfers(bytes32)": FunctionFragment;
    "deposit(address,uint256,uint64,address,uint64)": FunctionFragment;
    "depositNative(uint256,uint64,address,uint64)": FunctionFragment;
    "epochLength()": FunctionFragment;
    "epochVolumeCaps(address)": FunctionFragment;
    "epochVolumes(address)": FunctionFragment;
    "executeDelayedTransfer(bytes32)": FunctionFragment;
    "governors(address)": FunctionFragment;
    "isGovernor(address)": FunctionFragment;
    "isPauser(address)": FunctionFragment;
    "lastOpTimestamps(address)": FunctionFragment;
    "maxDeposit(address)": FunctionFragment;
    "minDeposit(address)": FunctionFragment;
    "nativeWrap()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "pausers(address)": FunctionFragment;
    "records(bytes32)": FunctionFragment;
    "removeGovernor(address)": FunctionFragment;
    "removePauser(address)": FunctionFragment;
    "renounceGovernor()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "renouncePauser()": FunctionFragment;
    "setDelayPeriod(uint256)": FunctionFragment;
    "setDelayThresholds(address[],uint256[])": FunctionFragment;
    "setEpochLength(uint256)": FunctionFragment;
    "setEpochVolumeCaps(address[],uint256[])": FunctionFragment;
    "setMaxDeposit(address[],uint256[])": FunctionFragment;
    "setMinDeposit(address[],uint256[])": FunctionFragment;
    "setWrap(address)": FunctionFragment;
    "sigsVerifier()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "withdraw(bytes,bytes[],address[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addGovernor", values: [string]): string;
  encodeFunctionData(functionFragment: "addPauser", values: [string]): string;
  encodeFunctionData(functionFragment: "delayPeriod", values?: undefined): string;
  encodeFunctionData(functionFragment: "delayThresholds", values: [string]): string;
  encodeFunctionData(functionFragment: "delayedTransfers", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, BigNumberish, string, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "depositNative",
    values: [BigNumberish, BigNumberish, string, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "epochLength", values?: undefined): string;
  encodeFunctionData(functionFragment: "epochVolumeCaps", values: [string]): string;
  encodeFunctionData(functionFragment: "epochVolumes", values: [string]): string;
  encodeFunctionData(functionFragment: "executeDelayedTransfer", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "governors", values: [string]): string;
  encodeFunctionData(functionFragment: "isGovernor", values: [string]): string;
  encodeFunctionData(functionFragment: "isPauser", values: [string]): string;
  encodeFunctionData(functionFragment: "lastOpTimestamps", values: [string]): string;
  encodeFunctionData(functionFragment: "maxDeposit", values: [string]): string;
  encodeFunctionData(functionFragment: "minDeposit", values: [string]): string;
  encodeFunctionData(functionFragment: "nativeWrap", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pausers", values: [string]): string;
  encodeFunctionData(functionFragment: "records", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "removeGovernor", values: [string]): string;
  encodeFunctionData(functionFragment: "removePauser", values: [string]): string;
  encodeFunctionData(functionFragment: "renounceGovernor", values?: undefined): string;
  encodeFunctionData(functionFragment: "renounceOwnership", values?: undefined): string;
  encodeFunctionData(functionFragment: "renouncePauser", values?: undefined): string;
  encodeFunctionData(functionFragment: "setDelayPeriod", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setDelayThresholds", values: [string[], BigNumberish[]]): string;
  encodeFunctionData(functionFragment: "setEpochLength", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "setEpochVolumeCaps", values: [string[], BigNumberish[]]): string;
  encodeFunctionData(functionFragment: "setMaxDeposit", values: [string[], BigNumberish[]]): string;
  encodeFunctionData(functionFragment: "setMinDeposit", values: [string[], BigNumberish[]]): string;
  encodeFunctionData(functionFragment: "setWrap", values: [string]): string;
  encodeFunctionData(functionFragment: "sigsVerifier", values?: undefined): string;
  encodeFunctionData(functionFragment: "transferOwnership", values: [string]): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values: [BytesLike, BytesLike[], string[], BigNumberish[]]): string;

  decodeFunctionResult(functionFragment: "addGovernor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delayPeriod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delayThresholds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delayedTransfers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositNative", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochLength", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochVolumeCaps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochVolumes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executeDelayedTransfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isGovernor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastOpTimestamps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nativeWrap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pausers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeGovernor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removePauser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceGovernor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renouncePauser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDelayPeriod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDelayThresholds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setEpochLength", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setEpochVolumeCaps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMaxDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMinDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setWrap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sigsVerifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "DelayPeriodUpdated(uint256)": EventFragment;
    "DelayThresholdUpdated(address,uint256)": EventFragment;
    "DelayedTransferAdded(bytes32)": EventFragment;
    "DelayedTransferExecuted(bytes32,address,address,uint256)": EventFragment;
    "Deposited(bytes32,address,address,uint256,uint64,address,uint64)": EventFragment;
    "EpochLengthUpdated(uint256)": EventFragment;
    "EpochVolumeUpdated(address,uint256)": EventFragment;
    "GovernorAdded(address)": EventFragment;
    "GovernorRemoved(address)": EventFragment;
    "MaxDepositUpdated(address,uint256)": EventFragment;
    "MinDepositUpdated(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "PauserAdded(address)": EventFragment;
    "PauserRemoved(address)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Withdrawn(bytes32,address,address,uint256,uint64,bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DelayPeriodUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DelayThresholdUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DelayedTransferAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DelayedTransferExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EpochLengthUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EpochVolumeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernorAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernorRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaxDepositUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MinDepositUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauserAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauserRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
}

export type DelayPeriodUpdatedEvent = TypedEvent<[BigNumber], { period: BigNumber }>;

export type DelayPeriodUpdatedEventFilter = TypedEventFilter<DelayPeriodUpdatedEvent>;

export type DelayThresholdUpdatedEvent = TypedEvent<[string, BigNumber], { token: string; threshold: BigNumber }>;

export type DelayThresholdUpdatedEventFilter = TypedEventFilter<DelayThresholdUpdatedEvent>;

export type DelayedTransferAddedEvent = TypedEvent<[string], { id: string }>;

export type DelayedTransferAddedEventFilter = TypedEventFilter<DelayedTransferAddedEvent>;

export type DelayedTransferExecutedEvent = TypedEvent<
  [string, string, string, BigNumber],
  { id: string; receiver: string; token: string; amount: BigNumber }
>;

export type DelayedTransferExecutedEventFilter = TypedEventFilter<DelayedTransferExecutedEvent>;

export type DepositedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string, BigNumber],
  {
    depositId: string;
    depositor: string;
    token: string;
    amount: BigNumber;
    mintChainId: BigNumber;
    mintAccount: string;
    nonce: BigNumber;
  }
>;

export type DepositedEventFilter = TypedEventFilter<DepositedEvent>;

export type EpochLengthUpdatedEvent = TypedEvent<[BigNumber], { length: BigNumber }>;

export type EpochLengthUpdatedEventFilter = TypedEventFilter<EpochLengthUpdatedEvent>;

export type EpochVolumeUpdatedEvent = TypedEvent<[string, BigNumber], { token: string; cap: BigNumber }>;

export type EpochVolumeUpdatedEventFilter = TypedEventFilter<EpochVolumeUpdatedEvent>;

export type GovernorAddedEvent = TypedEvent<[string], { account: string }>;

export type GovernorAddedEventFilter = TypedEventFilter<GovernorAddedEvent>;

export type GovernorRemovedEvent = TypedEvent<[string], { account: string }>;

export type GovernorRemovedEventFilter = TypedEventFilter<GovernorRemovedEvent>;

export type MaxDepositUpdatedEvent = TypedEvent<[string, BigNumber], { token: string; amount: BigNumber }>;

export type MaxDepositUpdatedEventFilter = TypedEventFilter<MaxDepositUpdatedEvent>;

export type MinDepositUpdatedEvent = TypedEvent<[string, BigNumber], { token: string; amount: BigNumber }>;

export type MinDepositUpdatedEventFilter = TypedEventFilter<MinDepositUpdatedEvent>;

export type OwnershipTransferredEvent = TypedEvent<[string, string], { previousOwner: string; newOwner: string }>;

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>;

export type PausedEvent = TypedEvent<[string], { account: string }>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export type PauserAddedEvent = TypedEvent<[string], { account: string }>;

export type PauserAddedEventFilter = TypedEventFilter<PauserAddedEvent>;

export type PauserRemovedEvent = TypedEvent<[string], { account: string }>;

export type PauserRemovedEventFilter = TypedEventFilter<PauserRemovedEvent>;

export type UnpausedEvent = TypedEvent<[string], { account: string }>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export type WithdrawnEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string, string],
  {
    withdrawId: string;
    receiver: string;
    token: string;
    amount: BigNumber;
    refChainId: BigNumber;
    refId: string;
    burnAccount: string;
  }
>;

export type WithdrawnEventFilter = TypedEventFilter<WithdrawnEvent>;

export interface OriginalTokenVaultV2 extends BaseContract {
  contractName: "OriginalTokenVaultV2";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OriginalTokenVaultV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addGovernor(
      _account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    addPauser(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    delayPeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    delayThresholds(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    delayedTransfers(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        receiver: string;
        token: string;
        amount: BigNumber;
        timestamp: BigNumber;
      }
    >;

    deposit(
      _token: string,
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    depositNative(
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    epochLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochVolumeCaps(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    epochVolumes(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    executeDelayedTransfer(
      id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    governors(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isGovernor(_account: string, overrides?: CallOverrides): Promise<[boolean]>;

    isPauser(account: string, overrides?: CallOverrides): Promise<[boolean]>;

    lastOpTimestamps(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    maxDeposit(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    minDeposit(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    nativeWrap(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pausers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    records(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    removeGovernor(
      _account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    removePauser(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    renounceGovernor(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    renouncePauser(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    setDelayPeriod(
      _period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setDelayThresholds(
      _tokens: string[],
      _thresholds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setEpochLength(
      _length: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setEpochVolumeCaps(
      _tokens: string[],
      _caps: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setMaxDeposit(
      _tokens: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setMinDeposit(
      _tokens: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setWrap(_weth: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    sigsVerifier(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    unpause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    withdraw(
      _request: BytesLike,
      _sigs: BytesLike[],
      _signers: string[],
      _powers: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  addGovernor(
    _account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  addPauser(account: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  delayPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  delayThresholds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  delayedTransfers(
    arg0: BytesLike,
    overrides?: CallOverrides,
  ): Promise<
    [string, string, BigNumber, BigNumber] & {
      receiver: string;
      token: string;
      amount: BigNumber;
      timestamp: BigNumber;
    }
  >;

  deposit(
    _token: string,
    _amount: BigNumberish,
    _mintChainId: BigNumberish,
    _mintAccount: string,
    _nonce: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  depositNative(
    _amount: BigNumberish,
    _mintChainId: BigNumberish,
    _mintAccount: string,
    _nonce: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  epochLength(overrides?: CallOverrides): Promise<BigNumber>;

  epochVolumeCaps(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  epochVolumes(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  executeDelayedTransfer(
    id: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  governors(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isGovernor(_account: string, overrides?: CallOverrides): Promise<boolean>;

  isPauser(account: string, overrides?: CallOverrides): Promise<boolean>;

  lastOpTimestamps(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  maxDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  minDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  nativeWrap(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pausers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  records(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  removeGovernor(
    _account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  removePauser(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  renounceGovernor(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  renouncePauser(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  setDelayPeriod(
    _period: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setDelayThresholds(
    _tokens: string[],
    _thresholds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setEpochLength(
    _length: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setEpochVolumeCaps(
    _tokens: string[],
    _caps: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setMaxDeposit(
    _tokens: string[],
    _amounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setMinDeposit(
    _tokens: string[],
    _amounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setWrap(_weth: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  sigsVerifier(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  unpause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  withdraw(
    _request: BytesLike,
    _sigs: BytesLike[],
    _signers: string[],
    _powers: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    addGovernor(_account: string, overrides?: CallOverrides): Promise<void>;

    addPauser(account: string, overrides?: CallOverrides): Promise<void>;

    delayPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    delayThresholds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    delayedTransfers(
      arg0: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        receiver: string;
        token: string;
        amount: BigNumber;
        timestamp: BigNumber;
      }
    >;

    deposit(
      _token: string,
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    depositNative(
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    epochLength(overrides?: CallOverrides): Promise<BigNumber>;

    epochVolumeCaps(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    epochVolumes(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    executeDelayedTransfer(id: BytesLike, overrides?: CallOverrides): Promise<void>;

    governors(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isGovernor(_account: string, overrides?: CallOverrides): Promise<boolean>;

    isPauser(account: string, overrides?: CallOverrides): Promise<boolean>;

    lastOpTimestamps(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    maxDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    minDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    nativeWrap(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pausers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    records(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    removeGovernor(_account: string, overrides?: CallOverrides): Promise<void>;

    removePauser(account: string, overrides?: CallOverrides): Promise<void>;

    renounceGovernor(overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    renouncePauser(overrides?: CallOverrides): Promise<void>;

    setDelayPeriod(_period: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setDelayThresholds(_tokens: string[], _thresholds: BigNumberish[], overrides?: CallOverrides): Promise<void>;

    setEpochLength(_length: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setEpochVolumeCaps(_tokens: string[], _caps: BigNumberish[], overrides?: CallOverrides): Promise<void>;

    setMaxDeposit(_tokens: string[], _amounts: BigNumberish[], overrides?: CallOverrides): Promise<void>;

    setMinDeposit(_tokens: string[], _amounts: BigNumberish[], overrides?: CallOverrides): Promise<void>;

    setWrap(_weth: string, overrides?: CallOverrides): Promise<void>;

    sigsVerifier(overrides?: CallOverrides): Promise<string>;

    transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    withdraw(
      _request: BytesLike,
      _sigs: BytesLike[],
      _signers: string[],
      _powers: BigNumberish[],
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {
    "DelayPeriodUpdated(uint256)"(period?: null): DelayPeriodUpdatedEventFilter;
    DelayPeriodUpdated(period?: null): DelayPeriodUpdatedEventFilter;

    "DelayThresholdUpdated(address,uint256)"(token?: null, threshold?: null): DelayThresholdUpdatedEventFilter;
    DelayThresholdUpdated(token?: null, threshold?: null): DelayThresholdUpdatedEventFilter;

    "DelayedTransferAdded(bytes32)"(id?: null): DelayedTransferAddedEventFilter;
    DelayedTransferAdded(id?: null): DelayedTransferAddedEventFilter;

    "DelayedTransferExecuted(bytes32,address,address,uint256)"(
      id?: null,
      receiver?: null,
      token?: null,
      amount?: null,
    ): DelayedTransferExecutedEventFilter;
    DelayedTransferExecuted(
      id?: null,
      receiver?: null,
      token?: null,
      amount?: null,
    ): DelayedTransferExecutedEventFilter;

    "Deposited(bytes32,address,address,uint256,uint64,address,uint64)"(
      depositId?: null,
      depositor?: null,
      token?: null,
      amount?: null,
      mintChainId?: null,
      mintAccount?: null,
      nonce?: null,
    ): DepositedEventFilter;
    Deposited(
      depositId?: null,
      depositor?: null,
      token?: null,
      amount?: null,
      mintChainId?: null,
      mintAccount?: null,
      nonce?: null,
    ): DepositedEventFilter;

    "EpochLengthUpdated(uint256)"(length?: null): EpochLengthUpdatedEventFilter;
    EpochLengthUpdated(length?: null): EpochLengthUpdatedEventFilter;

    "EpochVolumeUpdated(address,uint256)"(token?: null, cap?: null): EpochVolumeUpdatedEventFilter;
    EpochVolumeUpdated(token?: null, cap?: null): EpochVolumeUpdatedEventFilter;

    "GovernorAdded(address)"(account?: null): GovernorAddedEventFilter;
    GovernorAdded(account?: null): GovernorAddedEventFilter;

    "GovernorRemoved(address)"(account?: null): GovernorRemovedEventFilter;
    GovernorRemoved(account?: null): GovernorRemovedEventFilter;

    "MaxDepositUpdated(address,uint256)"(token?: null, amount?: null): MaxDepositUpdatedEventFilter;
    MaxDepositUpdated(token?: null, amount?: null): MaxDepositUpdatedEventFilter;

    "MinDepositUpdated(address,uint256)"(token?: null, amount?: null): MinDepositUpdatedEventFilter;
    MinDepositUpdated(token?: null, amount?: null): MinDepositUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "PauserAdded(address)"(account?: null): PauserAddedEventFilter;
    PauserAdded(account?: null): PauserAddedEventFilter;

    "PauserRemoved(address)"(account?: null): PauserRemovedEventFilter;
    PauserRemoved(account?: null): PauserRemovedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Withdrawn(bytes32,address,address,uint256,uint64,bytes32,address)"(
      withdrawId?: null,
      receiver?: null,
      token?: null,
      amount?: null,
      refChainId?: null,
      refId?: null,
      burnAccount?: null,
    ): WithdrawnEventFilter;
    Withdrawn(
      withdrawId?: null,
      receiver?: null,
      token?: null,
      amount?: null,
      refChainId?: null,
      refId?: null,
      burnAccount?: null,
    ): WithdrawnEventFilter;
  };

  estimateGas: {
    addGovernor(_account: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    addPauser(account: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    delayPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    delayThresholds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    delayedTransfers(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      _token: string,
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    depositNative(
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    epochLength(overrides?: CallOverrides): Promise<BigNumber>;

    epochVolumeCaps(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    epochVolumes(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    executeDelayedTransfer(
      id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    governors(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isGovernor(_account: string, overrides?: CallOverrides): Promise<BigNumber>;

    isPauser(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    lastOpTimestamps(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    maxDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    minDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    nativeWrap(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pausers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    records(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    removeGovernor(_account: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    removePauser(account: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    renounceGovernor(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    renouncePauser(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    setDelayPeriod(
      _period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setDelayThresholds(
      _tokens: string[],
      _thresholds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setEpochLength(
      _length: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setEpochVolumeCaps(
      _tokens: string[],
      _caps: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setMaxDeposit(
      _tokens: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setMinDeposit(
      _tokens: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setWrap(_weth: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    sigsVerifier(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    withdraw(
      _request: BytesLike,
      _sigs: BytesLike[],
      _signers: string[],
      _powers: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addGovernor(
      _account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    addPauser(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    delayPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delayThresholds(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delayedTransfers(arg0: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      _token: string,
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    depositNative(
      _amount: BigNumberish,
      _mintChainId: BigNumberish,
      _mintAccount: string,
      _nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    epochLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochVolumeCaps(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochVolumes(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeDelayedTransfer(
      id: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    governors(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isGovernor(_account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isPauser(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastOpTimestamps(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxDeposit(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minDeposit(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nativeWrap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pausers(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    records(arg0: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeGovernor(
      _account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    removePauser(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    renounceGovernor(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    renouncePauser(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    setDelayPeriod(
      _period: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setDelayThresholds(
      _tokens: string[],
      _thresholds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setEpochLength(
      _length: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setEpochVolumeCaps(
      _tokens: string[],
      _caps: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setMaxDeposit(
      _tokens: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setMinDeposit(
      _tokens: string[],
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setWrap(_weth: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    sigsVerifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    unpause(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    withdraw(
      _request: BytesLike,
      _sigs: BytesLike[],
      _signers: string[],
      _powers: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
